(()=>{"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY="blendEnglish.v3", OLDKEY="blendEnglish.v1";
const LANGS=[["ja","日本語","ja-JP"],["en","English","en-US"],["zh-CN","中文（简体）","zh-CN"],["zh-TW","中文（繁體）","zh-TW"],["ko","한국어","ko-KR"],["es","Español","es-ES"],["fr","Français","fr-FR"],["de","Deutsch","de-DE"],["it","Italiano","it-IT"],["pt","Português","pt-BR"],["ru","Русский","ru-RU"],["ar","العربية","ar-SA"],["hi","हिन्दी","hi-IN"],["id","Bahasa Indonesia","id-ID"],["th","ไทย","th-TH"],["vi","Tiếng Việt","vi-VN"],["nl","Nederlands","nl-NL"],["pl","Polski","pl-PL"]];
const SAMPLE="今日は文化祭の二日目です。朝から校内にはたくさんの人が集まっています。生徒たちは自分たちの企画を少しでも楽しんでもらおうと、一生懸命に声をかけています。教室の前では長い列ができています。それでも、待っている人たちは楽しそうに友達と話しています。昨日より少し疲れていますが、学校全体には特別な熱気があります。";
const ARTICLE_SAMPLE="<h2>好きなことを、そのまま学びに変える</h2><p>語学学習を続けるのが難しい理由の一つは、教材そのものに興味を持てないことです。毎日読むニュースや、好きなスポーツの記事、仕事で必要な情報がそのまま教材になれば、学習のためだけの時間を新しく作る必要はありません。</p><p>ただし、最初から全文を外国語にすると負荷が高くなります。そこで、文章の一部だけを外国語にします。前後の文脈が残っていれば、分からない単語があっても意味を推測しやすくなります。</p><blockquote>理解を止めずに、外国語に触れる量を増やす。</blockquote><p>この考え方が、このリーダーの中心です。</p>";
let state=loadState(), activeBubble=null, browserTranslator=null, toastTimer=null;
function base(){return{settings:{sourceLang:"ja",targetLang:"en",style:"natural",level:"B1",mix:40,speakerGender:"unspecified",politeness:"normal",audience:"general",speechNote:""},activeId:null,articles:[],saved:[]}}
function migrateOld(){try{let old=JSON.parse(localStorage.getItem(OLDKEY));if(!old?.articles?.length)return null;let st=base();st.articles=old.articles.map(a=>({id:a.id||uid(),title:a.title||"旧データ",createdAt:a.createdAt||new Date().toISOString(),updatedAt:a.updatedAt||new Date().toISOString(),sourceLang:"ja",targetLang:"en",mix:a.mix??40,seed:a.seed??Math.random(),style:"natural",level:a.level||"B1",items:[{type:"text",tag:"p",sentences:(a.sentences||[]).map((s,i)=>({id:`m${i}`,source:s.ja||"",target:s.en||""}))}],revealed:[]}));st.saved=(old.saved||[]).map(x=>({id:x.id||uid(),articleId:x.articleId,title:x.title||"",source:x.ja||"",target:x.en||"",lang:"en"}));return st}catch{return null}}
function loadState(){try{return Object.assign(base(),JSON.parse(localStorage.getItem(KEY))||migrateOld()||{})}catch{return migrateOld()||base()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function uid(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`}
function info(code){return LANGS.find(x=>x[0]===code)||[code,code,code]} function lname(code){return info(code)[1]} function scode(code){return info(code)[2]}
function toast(msg){let t=$("#toast");t.textContent=msg;t.classList.remove("hidden");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.add("hidden"),2200)}
function view(id){$$(".view").forEach(v=>v.classList.toggle("active",v.id===id));$("#backBtn").classList.toggle("hidden",id==="homeView");closeBubble();scrollTo({top:0,behavior:"smooth"})}
function active(){return state.articles.find(a=>a.id===state.activeId)||null}
function fillLang(){for(const sel of [$("#sourceLang"),$("#targetLang")]){sel.innerHTML="";LANGS.forEach(([c,n])=>{let o=document.createElement("option");o.value=c;o.textContent=n;sel.append(o)})}$("#sourceLang").value=state.settings.sourceLang;$("#targetLang").value=state.settings.targetLang}
function count(){let n=$("#sourceEditor").innerText.trim().length;$("#charCount").textContent=`${n} / 10000`;$("#charCount").style.color=n>10000?"var(--red)":""}
function split(text){text=text.replace(/\s+/g," ").trim();if(!text)return[];let p=text.match(/[^。！？!?]+[。！？!?]?|[^.!?]+[.!?]+/g);if(!p)p=[text];return p.map(x=>x.trim()).filter(Boolean)}
function cleanUrl(v){try{let u=new URL(v,location.href);if(["http:","https:"].includes(u.protocol))return u.href}catch{}return""}
function sanitize(html){let d=new DOMParser().parseFromString(html,"text/html"),allow=new Set(["P","DIV","H1","H2","H3","H4","UL","OL","LI","B","STRONG","I","EM","A","IMG","BR","BLOCKQUOTE"]);[...d.body.querySelectorAll("*")].forEach(el=>{if(!allow.has(el.tagName)){el.replaceWith(...el.childNodes);return}let href=el.tagName==="A"?cleanUrl(el.getAttribute("href")||""):"",src=el.tagName==="IMG"?cleanUrl(el.getAttribute("src")||""):"";[...el.attributes].forEach(a=>el.removeAttribute(a.name));if(el.tagName==="A"&&href){el.href=href;el.target="_blank";el.rel="noopener"}if(el.tagName==="IMG"){if(!src)el.remove();else{el.src=src;el.alt=""}}});return d.body.innerHTML}
function extract(){let items=[],sid=0,root=$("#sourceEditor");function walk(el){if(el.nodeType!==1)return;let tag=el.tagName.toLowerCase();if(tag==="img"){let src=cleanUrl(el.getAttribute("src")||"");if(src)items.push({type:"image",src,alt:""});return}if(["p","h1","h2","h3","h4","li","blockquote"].includes(tag)){let t=el.innerText?.trim()||"";if(t)items.push({type:"text",tag:tag==="li"?"p":tag,sentences:split(t).map(x=>({id:`s${++sid}`,source:x,target:""}))});return}[...el.children].forEach(walk)}[...root.children].forEach(walk);if(!items.length&&root.innerText.trim())items=[{type:"text",tag:"p",sentences:split(root.innerText).map(x=>({id:`s${++sid}`,source:x,target:""}))}];return items}
function sentences(items){return items.filter(x=>x.type==="text").flatMap(x=>x.sentences)}
function prompt(items){let ss=sentences(items),s=state.settings,style=s.style==="natural"?"Use natural, idiomatic wording that a real speaker would use.":s.style==="faithful"?"Stay close to the source meaning and structure while remaining grammatical.":`Use vocabulary and syntax appropriate for ${s.level}, while keeping the target language natural.`;return `Create sentence-level bilingual reading data.\n\nSOURCE LANGUAGE: ${lname(s.sourceLang)} (${s.sourceLang})\nTARGET LANGUAGE: ${lname(s.targetLang)} (${s.targetLang})\nSTYLE: ${style}\nSPEAKER: ${s.speakerGender}\nPOLITENESS: ${s.politeness}\nAUDIENCE: ${s.audience}\nEXTRA CONTEXT: ${s.speechNote||"none"}\n\nTranslate every numbered sentence. Keep exact order. Do not merge or split.\nWhere gender, politeness, relationship, or register changes wording, respect the settings.\nAvoid stiff machine-translation phrasing. Preserve names, dates, numbers, and facts.\n\nReturn valid JSON only, with no markdown:\n{\"title\":\"short title in the source language\",\"translations\":[{\"id\":\"s1\",\"source\":\"exact source sentence\",\"target\":\"translation\"}]}\n\nInclude all ${ss.length} sentences. IDs and source sentences must match exactly.\n\nSENTENCES\n${ss.map(x=>`${x.id}. ${x.source}`).join("\n")}`}
function parse(raw,items){raw=raw.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"");let o=JSON.parse(raw);if(!o?.translations?.length)throw Error("translations が見つかりません。");let map=new Map(o.translations.map(x=>[String(x.id),x])),cp=structuredClone(items);for(const s of sentences(cp)){let t=map.get(s.id);if(!t||!String(t.target||"").trim())throw Error(`${s.id} の翻訳がありません。`);s.target=String(t.target).trim()}return{title:String(o.title||"新しい文章").slice(0,100),items:cp}}
async function availability(){if(!("Translator"in window))return"unavailable";try{return await Translator.availability({sourceLanguage:state.settings.sourceLang,targetLanguage:state.settings.targetLang})}catch{return"unavailable"}}
async function status(){let a=await availability();$("#translationStatus").textContent=a==="available"?"この端末で直接翻訳できます。":a==="unavailable"?"この言語ペアはChatGPT連携で作成します。":"初回のみ翻訳モデルを準備します。"}
async function direct(items){browserTranslator=await Translator.create({sourceLanguage:state.settings.sourceLang,targetLanguage:state.settings.targetLang});let cp=structuredClone(items),ss=sentences(cp);for(let i=0;i<ss.length;i++){toast(`翻訳中 ${i+1} / ${ss.length}`);ss[i].target=await browserTranslator.translate(ss[i].source)}return{title:"新しい文章",items:cp}}
function make(data){let s=state.settings,a={id:uid(),title:data.title||"新しい文章",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),sourceLang:s.sourceLang,targetLang:s.targetLang,style:s.style,level:s.level,mix:s.mix??40,seed:Math.random(),items:data.items,revealed:[]};state.articles.unshift(a);state.articles=state.articles.slice(0,100);state.activeId=a.id;save();openReader(a.id)}
function hash(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function tset(a){let ss=sentences(a.items),n=Math.round(ss.length*a.mix/100);return new Set(ss.map(s=>({id:s.id,score:hash(`${a.seed}-${s.id}-${s.source}`)})).sort((x,y)=>x.score-y.score).slice(0,n).map(x=>x.id))}
function render(){let a=active();if(!a)return view("homeView");$("#readerTitle").value=a.title;$("#readerMeta").textContent=`${lname(a.sourceLang)} × ${lname(a.targetLang)}・${sentences(a.items).length}文・この端末に保存`;$("#mixSlider").value=a.mix;$("#targetPercent").textContent=`${a.mix}%`;$("#sourcePercent").textContent=`${100-a.mix}%`;$("#targetLangLabel").textContent=lname(a.targetLang);$("#sourceLangLabel").textContent=lname(a.sourceLang);let set=tset(a),doc=$("#readerArticle");doc.innerHTML="";a.items.forEach(item=>{if(item.type==="image"){let img=document.createElement("img");img.className="reader-image";img.src=item.src;img.alt=item.alt||"";img.loading="lazy";doc.append(img);return}let el=document.createElement(item.tag||"p");el.className="block";item.sentences.forEach((s,i)=>{let isTarget=set.has(s.id),b=document.createElement("button");b.className=`sentence ${isTarget?"target":"source"}`;b.dataset.sid=s.id;b.dataset.side=isTarget?"target":"source";b.textContent=isTarget?s.target:s.source;b.lang=isTarget?a.targetLang:a.sourceLang;el.append(b);if(i<item.sentences.length-1)el.append(document.createTextNode(" "))});doc.append(el)});meter()}
function openReader(id){state.activeId=id;save();render();view("readerView")}
function byid(a,id){return sentences(a.items).find(s=>s.id===id)}
function showBubble(btn,text,lang,s){activeBubble={sentence:s,lang,text};$("#bubbleText").textContent=text;$("#bubbleLabel").textContent=lname(lang);$("#bubbleSave").textContent=state.saved.some(x=>x.articleId===state.activeId&&x.sentenceId===s.id)?"★ 保存済み":"☆ 覚える";let b=$("#translationBubble");b.classList.remove("hidden");requestAnimationFrame(()=>{let r=btn.getBoundingClientRect(),bw=b.offsetWidth,bh=b.offsetHeight,left=Math.max(12,Math.min(innerWidth-bw-12,r.left+r.width/2-bw/2)),top=r.top-bh-12;if(top<8)top=Math.min(innerHeight-bh-8,r.bottom+12);b.style.left=`${left}px`;b.style.top=`${top}px`;b.style.setProperty("--arrow-left",`${Math.max(18,Math.min(bw-18,r.left+r.width/2-left))}px`)})}
function tap(btn){let a=active(),s=byid(a,btn.dataset.sid);if(!s)return;let target=btn.dataset.side==="target";if(target&&!a.revealed.includes(s.id))a.revealed.push(s.id);a.updatedAt=new Date().toISOString();save();showBubble(btn,target?s.source:s.target,target?a.sourceLang:a.targetLang,s);meter()}
function closeBubble(){$("#translationBubble").classList.add("hidden");activeBubble=null}
function setMix(v){let a=active();if(!a)return;a.mix=Math.max(0,Math.min(100,Math.round(v/10)*10));state.settings.mix=a.mix;a.revealed=[];save();render();closeBubble()}
function remix(){let a=active();if(!a)return;a.seed=Math.random();a.revealed=[];save();render();closeBubble();toast("配置を混ぜ直しました")}
function speak(text,lang){if(!("speechSynthesis"in window))return toast("読み上げ非対応です。");speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang=scode(lang);u.rate=.92;speechSynthesis.speak(u)}
async function speakTargets(){let a=active();if(!a)return;let set=tset(a),ss=sentences(a.items).filter(s=>set.has(s.id));if(!ss.length)return toast("学習言語の文がありません。");speechSynthesis.cancel();for(const s of ss){await new Promise(res=>{let u=new SpeechSynthesisUtterance(s.target);u.lang=scode(a.targetLang);u.rate=.9;u.onend=res;u.onerror=res;speechSynthesis.speak(u)})}}
function meter(){let a=active();if(!a)return;let total=sentences(a.items).length,target=Math.round(total*a.mix/100),rev=new Set(a.revealed||[]).size,rate=target?rev/target:0;$("#revealBadge").textContent=`対訳確認 ${rev}文`;$("#meterFill").style.width=`${Math.min(100,rate*100)}%`;let btn=$("#applySuggestionBtn"),msg=$("#meterMessage"),next=a.mix;btn.classList.add("hidden");if(target<3){msg.textContent="学習言語の文が少ないため、まだ比率提案は出しません。";return}if(rate<=.15&&a.mix<100){next=Math.min(100,a.mix+10);msg.textContent=`対訳確認が少なめです。次は ${next}% に上げても読み続けられそうです。`}else if(rate>.35&&a.mix>10){next=Math.max(0,a.mix-10);msg.textContent=`対訳確認が多めです。いったん ${next}% に下げると、流れを保ちやすくなります。`}else msg.textContent=`今の ${a.mix}% がちょうどよさそうです。`;if(next!==a.mix){btn.textContent=`おすすめ ${next}% を試す`;btn.dataset.value=next;btn.classList.remove("hidden")}}
function saveBubble(){let a=active(),s=activeBubble?.sentence;if(!a||!s)return;let i=state.saved.findIndex(x=>x.articleId===a.id&&x.sentenceId===s.id);if(i>=0){state.saved.splice(i,1);toast("保存から外しました")}else{state.saved.unshift({id:uid(),articleId:a.id,sentenceId:s.id,title:a.title,source:s.source,target:s.target,lang:a.targetLang});toast("保存しました")}save();$("#bubbleSave").textContent=state.saved.some(x=>x.articleId===a.id&&x.sentenceId===s.id)?"★ 保存済み":"☆ 覚える"}
function history(){let l=$("#historyList");l.innerHTML="";if(!state.articles.length){l.innerHTML='<div class="empty">まだ履歴がありません。</div>';return}state.articles.forEach(a=>{let d=document.createElement("div");d.className="list-item";d.innerHTML=`<strong></strong><small></small><p></p><div class="list-actions"><button data-open="${a.id}">読む</button><button data-delete="${a.id}">削除</button></div>`;d.querySelector("strong").textContent=a.title;d.querySelector("small").textContent=`${lname(a.sourceLang)} → ${lname(a.targetLang)}・${a.mix}%`;d.querySelector("p").textContent=sentences(a.items).slice(0,2).map(s=>s.source).join(" ").slice(0,110);l.append(d)})}
function saved(){let l=$("#savedList");l.innerHTML="";if(!state.saved.length){l.innerHTML='<div class="empty">文をタップし、吹き出しの「☆ 覚える」で保存できます。</div>';return}state.saved.forEach(x=>{let d=document.createElement("div");d.className="list-item";d.innerHTML=`<strong></strong><p class="t"></p><p class="s"></p><div class="list-actions"><button data-speak="${x.id}">🔊 聞く</button><button data-remove="${x.id}">削除</button></div>`;d.querySelector("strong").textContent=x.title;d.querySelector(".t").textContent=x.target;d.querySelector(".s").textContent=x.source;l.append(d)})}
function modal(id){id==="historyModal"?history():saved();$("#"+id).classList.remove("hidden")}
function bind(){
 fillLang();$("#styleChips").querySelectorAll("button").forEach(b=>b.classList.toggle("selected",b.dataset.style===state.settings.style));$("#levelSelect").value=state.settings.level;$("#speakerGender").value=state.settings.speakerGender;$("#politeness").value=state.settings.politeness;$("#audience").value=state.settings.audience;$("#speechNote").value=state.settings.speechNote||"";
 $("#sourceEditor").addEventListener("input",count);$("#sourceEditor").addEventListener("paste",e=>{let h=e.clipboardData?.getData("text/html");if(h){e.preventDefault();document.execCommand("insertHTML",false,sanitize(h));setTimeout(count)}});
 $("#sampleBtn").onclick=()=>{$("#sourceEditor").innerText=SAMPLE;count()};$("#articleSampleBtn").onclick=()=>{$("#sourceEditor").innerHTML=ARTICLE_SAMPLE;count()};$("#clearBtn").onclick=()=>{$("#sourceEditor").innerHTML="";count()};
 $("#sourceLang").onchange=e=>{state.settings.sourceLang=e.target.value;save();status()};$("#targetLang").onchange=e=>{state.settings.targetLang=e.target.value;save();status()};$("#swapLangBtn").onclick=()=>{let a=$("#sourceLang").value,b=$("#targetLang").value;$("#sourceLang").value=b;$("#targetLang").value=a;state.settings.sourceLang=b;state.settings.targetLang=a;save();status()};
 $("#styleChips").onclick=e=>{let b=e.target.closest("button[data-style]");if(!b)return;state.settings.style=b.dataset.style;save();$$("#styleChips button").forEach(x=>x.classList.toggle("selected",x===b))};$("#levelSelect").onchange=e=>{state.settings.level=e.target.value;save()};$("#speakerGender").onchange=e=>{state.settings.speakerGender=e.target.value;save()};$("#politeness").onchange=e=>{state.settings.politeness=e.target.value;save()};$("#audience").onchange=e=>{state.settings.audience=e.target.value;save()};$("#speechNote").oninput=e=>{state.settings.speechNote=e.target.value;save()};
 $("#createMixBtn").onclick=async()=>{let text=$("#sourceEditor").innerText.trim();if(!text)return toast("まず文章を貼り付けてください。");if(text.length>10000)return toast("10,000文字以内にしてください。");if(state.settings.sourceLang===state.settings.targetLang)return toast("異なる言語を選んでください。");let items=extract(),avail=await availability();if(avail!=="unavailable"){try{return make(await direct(items))}catch(e){console.error(e);toast("端末翻訳に失敗。ChatGPT連携へ切り替えます。")}}$("#promptOutput").value=prompt(items);$("#jsonInput").value="";$("#jsonError").classList.add("hidden");view("bridgeView")};
 $("#copyPromptBtn").onclick=async()=>{try{await navigator.clipboard.writeText($("#promptOutput").value);toast("指示文をコピーしました")}catch{$("#promptOutput").select();document.execCommand("copy");toast("コピーしました")}};$("#pasteJsonBtn").onclick=async()=>{try{$("#jsonInput").value=await navigator.clipboard.readText()}catch{toast("長押しで貼り付けてください。")}};$("#importJsonBtn").onclick=()=>{try{let data=parse($("#jsonInput").value,extract());$("#jsonError").classList.add("hidden");make(data)}catch(e){$("#jsonError").textContent=`読み込めません：${e.message}`;$("#jsonError").classList.remove("hidden")}};
 $("#backBtn").onclick=()=>view("homeView");$("#homeBtn").onclick=()=>view("homeView");$("#historyBtn").onclick=()=>modal("historyModal");$("#savedBtn").onclick=$("#savedInReaderBtn").onclick=()=>modal("savedModal");$$('[data-close-modal]').forEach(x=>x.onclick=()=>$("#"+x.dataset.closeModal).classList.add("hidden"));
 $("#readerArticle").onclick=e=>{let b=e.target.closest(".sentence");if(b)tap(b)};$("#mixSlider").oninput=e=>setMix(+e.target.value);$("#minusRatio").onclick=()=>setMix((active()?.mix||0)-10);$("#plusRatio").onclick=()=>setMix((active()?.mix||0)+10);$("#remixBtn").onclick=remix;$("#readerTitle").onchange=e=>{let a=active();if(a){a.title=e.target.value.trim()||"新しい文章";save()}};
 $("#speakTargetsBtn").onclick=speakTargets;$("#resetTapsBtn").onclick=()=>{let a=active();if(a){a.revealed=[];save();meter();toast("計測をリセットしました")}};$("#applySuggestionBtn").onclick=e=>setMix(+e.target.dataset.value);
 $("#bubbleClose").onclick=closeBubble;$("#bubbleSpeak").onclick=()=>{if(activeBubble)speak(activeBubble.text,activeBubble.lang)};$("#bubbleSave").onclick=saveBubble;addEventListener("resize",closeBubble);addEventListener("scroll",closeBubble,{passive:true});
 $("#historyList").onclick=e=>{let o=e.target.closest("[data-open]"),d=e.target.closest("[data-delete]");if(o){$("#historyModal").classList.add("hidden");openReader(o.dataset.open)}if(d){state.articles=state.articles.filter(a=>a.id!==d.dataset.delete);state.saved=state.saved.filter(x=>x.articleId!==d.dataset.delete);if(state.activeId===d.dataset.delete)state.activeId=null;save();history()}};
 $("#savedList").onclick=e=>{let s=e.target.closest("[data-speak]"),r=e.target.closest("[data-remove]");if(s){let x=state.saved.find(v=>v.id===s.dataset.speak);if(x)speak(x.target,x.lang)}if(r){state.saved=state.saved.filter(v=>v.id!==r.dataset.remove);save();saved()}};
 count();status();if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}))
}
bind();
})();