(()=>{"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)],KEY="blendEnglish.v3",OLDKEY="blendEnglish.v1";
const LANGS=[["ja","日本語","ja-JP"],["en","English","en-US"],["zh-CN","中文（简体）","zh-CN"],["zh-TW","中文（繁體）","zh-TW"],["ko","한국어","ko-KR"],["es","Español","es-ES"],["fr","Français","fr-FR"],["de","Deutsch","de-DE"],["it","Italiano","it-IT"],["pt","Português","pt-BR"],["ru","Русский","ru-RU"],["ar","العربية","ar-SA"],["hi","हिन्दी","hi-IN"],["id","Bahasa Indonesia","id-ID"],["th","ไทย","th-TH"],["vi","Tiếng Việt","vi-VN"],["nl","Nederlands","nl-NL"],["pl","Polski","pl-PL"]];
const SAMPLE="今日は文化祭の二日目です。朝から校内にはたくさんの人が集まっています。生徒たちは自分たちの企画を少しでも楽しんでもらおうと、一生懸命に声をかけています。教室の前では長い列ができています。それでも、待っている人たちは楽しそうに友達と話しています。昨日より少し疲れていますが、学校全体には特別な熱気があります。";
const ARTICLE_SAMPLE="<h2>好きなことを、そのまま学びに変える</h2><p>語学学習を続けるのが難しい理由の一つは、教材そのものに興味を持てないことです。毎日読むニュースや、好きなスポーツの記事、仕事で必要な情報がそのまま教材になれば、学習のためだけの時間を新しく作る必要はありません。</p><p>ただし、最初から全文を外国語にすると負荷が高くなります。そこで、文章の一部だけを外国語にします。前後の文脈が残っていれば、分からない単語があっても意味を推測しやすくなります。</p><blockquote>理解を止めずに、外国語に触れる量を増やす。</blockquote><p>この考え方が、このリーダーの中心です。</p>";
let state=loadState(),activeSentenceId=null,activeBubbleSentence=null,browserTranslator=null,toastTimer=null;
function defaultState(){return{settings:{sourceLang:"ja",targetLang:"en",style:"natural",level:"B1",mix:40,speakerGender:"unspecified",politeness:"normal",audience:"general",speechNote:""},activeId:null,articles:[],saved:[]}}
function migrateOld(){try{let old=JSON.parse(localStorage.getItem(OLDKEY));if(!old?.articles?.length)return null;let st=defaultState();st.articles=old.articles.map(a=>({id:a.id||uid(),title:a.title||"旧データ",createdAt:a.createdAt||new Date().toISOString(),updatedAt:a.updatedAt||new Date().toISOString(),sourceLang:"ja",targetLang:"en",mix:a.mix??40,seed:a.seed??Math.random(),style:"natural",level:a.level||"B1",items:[{type:"text",tag:"p",sentences:(a.sentences||[]).map((s,i)=>({id:`m${i}`,source:s.ja||"",target:s.en||"",manual:null}))}],revealed:[]}));st.saved=(old.saved||[]).map(x=>({id:x.id||uid(),articleId:x.articleId,title:x.title||"",source:x.ja||"",target:x.en||"",lang:"en"}));return st}catch{return null}}
function loadState(){try{return Object.assign(defaultState(),JSON.parse(localStorage.getItem(KEY))||{})}catch{return migrateOld()||defaultState()}}function saveState(){localStorage.setItem(KEY,JSON.stringify(state))}function uid(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`}
function langInfo(c){return LANGS.find(x=>x[0]===c)||[c,c,c]}function langName(c){return langInfo(c)[1]}function speechCode(c){return langInfo(c)[2]}
function toast(m){let t=$("#toast");t.textContent=m;t.classList.remove("hidden");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.add("hidden"),2200)}
function showView(id){$$(".view").forEach(v=>v.classList.toggle("active",v.id===id));$("#backBtn").classList.toggle("hidden",id==="homeView");closeBubble();scrollTo({top:0,behavior:"smooth"})}function activeArticle(){return state.articles.find(a=>a.id===state.activeId)||null}
function fillLanguages(){for(const sel of [$("#sourceLang"),$("#targetLang")]){sel.innerHTML="";LANGS.forEach(([c,n])=>{let o=document.createElement("option");o.value=c;o.textContent=n;sel.append(o)})}$("#sourceLang").value=state.settings.sourceLang;$("#targetLang").value=state.settings.targetLang}
function safeURL(v,k){try{if(k==="img"&&v.startsWith("data:image/")&&v.length<700000)return v;let u=new URL(v,location.href);if(["http:","https:"].includes(u.protocol))return u.href}catch{}return""}
function sanitizeHTML(html){const d=new DOMParser().parseFromString(html,"text/html"),allowed=new Set(["P","DIV","H1","H2","H3","H4","H5","H6","UL","OL","LI","B","STRONG","I","EM","A","IMG","BR","BLOCKQUOTE"]);[...d.body.querySelectorAll("*")].forEach(el=>{let href=el.getAttribute("href"),src=el.getAttribute("src"),alt=el.getAttribute("alt");if(!allowed.has(el.tagName)){el.replaceWith(...el.childNodes);return}[...el.attributes].forEach(a=>el.removeAttribute(a.name));if(el.tagName==="A"){href=safeURL(href||"","link");if(href){el.setAttribute("href",href);el.setAttribute("target","_blank");el.setAttribute("rel","noopener")}}if(el.tagName==="IMG"){src=safeURL(src||"","img");if(!src){el.remove();return}el.setAttribute("src",src);el.setAttribute("alt",(alt||"").slice(0,160))}});return d.body.innerHTML}
function charCount(){let n=$("#sourceEditor").innerText.trim().length;$("#charCount").textContent=`${n} / 10000`;$("#charCount").style.color=n>10000?"var(--red)":""}
function splitSentences(text){text=text.replace(/\s+/g," ").trim();if(!text)return[];let p=text.match(/[^。！？!?]+[。！？!?]?|[^.!?]+[.!?]+/g);if(!p||p.join("").replace(/\s/g,"").length<text.replace(/\s/g,"").length*.8)p=[text];return p.map(s=>s.trim()).filter(Boolean)}
function extractItems(){let r=$("#sourceEditor"),items=[],sid=0;function walk(n){if(n.nodeType!==1)return;let t=n.tagName.toLowerCase();if(t==="img"){let src=safeURL(n.getAttribute("src")||"","img");if(src)items.push({type:"image",src,alt:(n.getAttribute("alt")||"").slice(0,160)});return}if(["p","h1","h2","h3","h4","h5","h6","li","blockquote"].includes(t)){let text=n.innerText?.trim()||n.textContent?.trim()||"";if(text)items.push({type:"text",tag:t==="li"?"p":t,sentences:splitSentences(text).map(s=>({id:`s${++sid}`,source:s,target:"",manual:null}))});return}[...n.children].forEach(walk)}[...r.children].forEach(walk);if(!items.length&&r.innerText.trim())items.push({type:"text",tag:"p",sentences:splitSentences(r.innerText).map(s=>({id:`s${++sid}`,source:s,target:"",manual:null}))});return items}
function flat(items){return items.filter(x=>x.type==="text").flatMap(x=>x.sentences)}
function prompt(items){let ss=flat(items),s=state.settings,style={natural:"Natural, idiomatic wording that a real speaker would use in this context.",faithful:"Stay close to the source meaning and structure, but keep the target language grammatical.",learner:`Use vocabulary and syntax appropriate for ${s.level}. Keep it natural, not childish.`}[s.style];return`You are creating sentence-level bilingual reading material.\n\nSOURCE LANGUAGE: ${langName(s.sourceLang)} (${s.sourceLang})\nTARGET LANGUAGE: ${langName(s.targetLang)} (${s.targetLang})\nTRANSLATION STYLE: ${style}\nSPEECH CONTEXT: Speaker=${s.speakerGender}; Politeness=${s.politeness}; Audience=${s.audience}; Additional context=${s.speechNote||"none"}.\n\nTranslate every numbered sentence. Keep the exact order. Do not merge or split sentences.\nFor languages where gender, politeness, social relationship, or register changes the wording, respect the speech context.\nAvoid artificial machine-translation phrasing. Preserve names, dates, numbers, and facts.\n\nReturn JSON only. No markdown and no explanation.\nExact shape:\n{\"title\":\"Short title in the source language\",\"translations\":[{\"id\":\"s1\",\"source\":\"exact source sentence\",\"target\":\"translation\"}]}\n\nRules:\n- Include all ${ss.length} sentences.\n- id must match exactly.\n- source must preserve the supplied source sentence.\n- target must not be empty.\n\nSENTENCES\n${ss.map(x=>`${x.id}. ${x.source}`).join("\n")}`}
function parse(raw,items){raw=raw.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"");let o=JSON.parse(raw);if(!o?.translations?.length)throw Error("translations が見つかりません。");let m=new Map(o.translations.map(x=>[String(x.id),x])),c=structuredClone(items);for(const s of flat(c)){let t=m.get(s.id);if(!t||!String(t.target||"").trim())throw Error(`${s.id} の翻訳がありません。`);s.target=String(t.target).trim()}return{title:String(o.title||"新しい文章").slice(0,100),items:c}}
async function availability(){if(!("Translator"in window))return"unavailable";try{return await Translator.availability({sourceLanguage:state.settings.sourceLang,targetLanguage:state.settings.targetLang})}catch{return"unavailable"}}
async function updateStatus(){let a=await availability();$("#translationStatus").textContent=a==="available"?"この端末で直接翻訳できます。":a==="unavailable"?"この言語ペアはChatGPT連携で作成します。":"初回のみ言語モデルを準備します。"}
async function direct(items){browserTranslator=await Translator.create({sourceLanguage:state.settings.sourceLang,targetLanguage:state.settings.targetLang});let c=structuredClone(items),ss=flat(c);for(let i=0;i<ss.length;i++){toast(`翻訳中 ${i+1} / ${ss.length}`);ss[i].target=await browserTranslator.translate(ss[i].source)}return{title:"新しい文章",items:c}}
function makeArticle(data){let s=state.settings,a={id:uid(),title:data.title||"新しい文章",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),sourceLang:s.sourceLang,targetLang:s.targetLang,style:s.style,level:s.level,mix:s.mix??40,seed:Math.random(),items:data.items,revealed:[]};state.articles.unshift(a);state.articles=state.articles.slice(0,100);state.activeId=a.id;saveState();openReader(a.id)}
function hash(x){let h=2166136261;for(let i=0;i<x.length;i++){h^=x.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}function targetSet(a){let ss=flat(a.items),n=Math.round(ss.length*a.mix/100),r=ss.map(s=>({id:s.id,score:hash(`${a.seed}-${s.id}-${s.source}`)})).sort((x,y)=>x.score-y.score);return new Set(r.slice(0,n).map(x=>x.id))}
function sentButton(a,s,set){let auto=set.has(s.id),show=s.manual==="target"?true:s.manual==="source"?false:auto,b=document.createElement("button");b.className=`sentence ${show?"target":"source"}${s.manual?" manually-swapped":""}`;b.dataset.sid=s.id;b.textContent=show?s.target:s.source;b.lang=show?a.targetLang:a.sourceLang;return b}
function renderReader(){let a=activeArticle();if(!a)return showView("homeView");$("#readerTitle").value=a.title;$("#readerMeta").textContent=`${langName(a.sourceLang)} × ${langName(a.targetLang)}・${flat(a.items).length}文・この端末に保存`;$("#mixSlider").value=a.mix;$("#targetPercent").textContent=`${a.mix}%`;$("#sourcePercent").textContent=`${100-a.mix}%`;$("#targetLangLabel").textContent=langName(a.targetLang);$("#sourceLangLabel").textContent=langName(a.sourceLang);let set=targetSet(a),d=$("#readerArticle");d.innerHTML="";a.items.forEach(it=>{if(it.type==="image"){let img=document.createElement("img");img.className="reader-image";img.src=it.src;img.alt=it.alt||"";img.loading="lazy";d.append(img);return}let el=document.createElement(it.tag||"p");el.className="block";it.sentences.forEach((s,i)=>{el.append(sentButton(a,s,set));if(i<it.sentences.length-1)el.append(document.createTextNode(" "))});d.append(el)});renderMeter()}
function openReader(id){state.activeId=id;saveState();renderReader();showView("readerView")}function findSentence(a,id){return flat(a.items).find(s=>s.id===id)}
function openBubble(btn,text,lang,s){activeSentenceId=s.id;activeBubbleSentence=s;$("#bubbleText").textContent=text;$("#bubbleLabel").textContent=langName(lang);$("#bubbleSave").textContent=state.saved.some(x=>x.articleId===state.activeId&&x.sentenceId===s.id)?"★ 保存済み":"☆ 覚える";let b=$("#translationBubble");b.classList.remove("hidden");requestAnimationFrame(()=>{let r=btn.getBoundingClientRect(),w=b.offsetWidth,h=b.offsetHeight,left=Math.max(12,Math.min(innerWidth-w-12,r.left+r.width/2-w/2)),top=r.top-h-12;if(top<8)top=Math.min(innerHeight-h-8,r.bottom+12);b.style.left=`${left}px`;b.style.top=`${top}px`;b.style.setProperty("--arrow-left",`${Math.max(18,Math.min(w-18,r.left+r.width/2-left))}px`)})}
function closeBubble(){$("#translationBubble").classList.add("hidden");activeSentenceId=null;activeBubbleSentence=null}
function toggleSentence(btn){let a=activeArticle(),s=findSentence(a,btn.dataset.sid);if(!s)return;let was=btn.classList.contains("target"),before=was?s.target:s.source,bl=was?a.targetLang:a.sourceLang;s.manual=was?"source":"target";if(was&&!a.revealed.includes(s.id))a.revealed.push(s.id);a.updatedAt=new Date().toISOString();saveState();renderReader();let nb=$(`.sentence[data-sid="${CSS.escape(s.id)}"]`);openBubble(nb||btn,before,bl,s)}
function setMix(v){let a=activeArticle();if(!a)return;a.mix=Math.max(0,Math.min(100,Math.round(v/10)*10));state.settings.mix=a.mix;flat(a.items).forEach(s=>s.manual=null);a.revealed=[];saveState();renderReader();closeBubble()}
function remix(){let a=activeArticle();if(!a)return;a.seed=Math.random();flat(a.items).forEach(s=>s.manual=null);a.revealed=[];saveState();renderReader();closeBubble();toast("配置を混ぜ直しました")}
function speak(text,lang){if(!("speechSynthesis"in window))return toast("読み上げ非対応です。");speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang=speechCode(lang);u.rate=.92;speechSynthesis.speak(u)}
async function speakTargets(){let a=activeArticle();if(!a)return;let set=targetSet(a),ss=flat(a.items).filter(s=>s.manual==="target"||(s.manual!=="source"&&set.has(s.id)));if(!ss.length)return toast("外国語表示の文がありません。");if(!("speechSynthesis"in window))return toast("読み上げ非対応です。");speechSynthesis.cancel();for(const s of ss)await new Promise(res=>{let u=new SpeechSynthesisUtterance(s.target);u.lang=speechCode(a.targetLang);u.rate=.9;u.onend=res;u.onerror=res;speechSynthesis.speak(u)})}
function renderMeter(){let a=activeArticle();if(!a)return;let total=flat(a.items).length,target=Math.max(0,Math.round(total*a.mix/100)),rev=new Set(a.revealed||[]).size,rate=target?rev/target:0;$("#revealBadge").textContent=`対訳確認 ${rev}文`;$("#meterFill").style.width=`${Math.min(100,rate*100)}%`;let b=$("#applySuggestionBtn"),m=$("#meterMessage");b.classList.add("hidden");if(target<3){m.textContent="外国語文が少ないため、まだ比率提案は出しません。";return}let next=a.mix;if(rate<=.15&&a.mix<100){next=Math.min(100,a.mix+10);m.textContent=`対訳確認が少なめです。次は ${next}% に上げても流れを保てそうです。`}else if(rate>.35&&a.mix>10){next=Math.max(0,a.mix-10);m.textContent=`対訳確認が多めです。いったん ${next}% に下げると、読む流れを保ちやすくなります。`}else m.textContent=`今の ${a.mix}% がちょうどよさそうです。別の文章でも試してみてください。`;if(next!==a.mix){b.textContent=`おすすめ ${next}% を試す`;b.dataset.value=next;b.classList.remove("hidden")}}
function saveSentence(){let a=activeArticle(),s=activeBubbleSentence;if(!a||!s)return;let i=state.saved.findIndex(x=>x.articleId===a.id&&x.sentenceId===s.id);if(i>=0){state.saved.splice(i,1);toast("保存から外しました")}else{state.saved.unshift({id:uid(),articleId:a.id,sentenceId:s.id,title:a.title,source:s.source,target:s.target,lang:a.targetLang});toast("保存しました")}saveState();$("#bubbleSave").textContent=state.saved.some(x=>x.articleId===a.id&&x.sentenceId===s.id)?"★ 保存済み":"☆ 覚える"}
function renderHistory(){let l=$("#historyList");l.innerHTML="";if(!state.articles.length){l.innerHTML='<div class="empty">まだ履歴がありません。</div>';return}state.articles.forEach(a=>{let d=document.createElement("div");d.className="list-item";d.innerHTML=`<strong></strong><small></small><p></p><div class="list-actions"><button data-open="${a.id}">読む</button><button data-delete="${a.id}">削除</button></div>`;d.querySelector("strong").textContent=a.title;d.querySelector("small").textContent=`${langName(a.sourceLang)} → ${langName(a.targetLang)}・${a.mix}%`;d.querySelector("p").textContent=flat(a.items).slice(0,2).map(s=>s.source).join(" ").slice(0,110);l.append(d)})}
function renderSaved(){let l=$("#savedList");l.innerHTML="";if(!state.saved.length){l.innerHTML='<div class="empty">文をタップし、吹き出しの「☆ 覚える」で保存できます。</div>';return}state.saved.forEach(x=>{let d=document.createElement("div");d.className="list-item";d.innerHTML=`<strong></strong><p class="target-text"></p><p class="source-text"></p><div class="list-actions"><button data-speak="${x.id}">🔊 聞く</button><button data-remove="${x.id}">削除</button></div>`;d.querySelector("strong").textContent=x.title;d.querySelector(".target-text").textContent=x.target;d.querySelector(".source-text").textContent=x.source;l.append(d)})}
function openModal(id){id==="historyModal"?renderHistory():renderSaved();$("#"+id).classList.remove("hidden")}
function bind(){fillLanguages();$$("#styleChips button").forEach(b=>b.classList.toggle("selected",b.dataset.style===state.settings.style));$("#levelSelect").value=state.settings.level;$("#speakerGender").value=state.settings.speakerGender;$("#politeness").value=state.settings.politeness;$("#audience").value=state.settings.audience;$("#speechNote").value=state.settings.speechNote||"";
$("#sourceEditor").addEventListener("input",charCount);$("#sourceEditor").addEventListener("paste",e=>{let h=e.clipboardData?.getData("text/html");if(h){e.preventDefault();document.execCommand("insertHTML",false,sanitizeHTML(h));setTimeout(charCount)}});$("#sampleBtn").onclick=()=>{$("#sourceEditor").innerText=SAMPLE;charCount()};$("#articleSampleBtn").onclick=()=>{$("#sourceEditor").innerHTML=ARTICLE_SAMPLE;charCount()};$("#clearBtn").onclick=()=>{$("#sourceEditor").innerHTML="";charCount()};
$("#sourceLang").onchange=e=>{state.settings.sourceLang=e.target.value;saveState();updateStatus()};$("#targetLang").onchange=e=>{state.settings.targetLang=e.target.value;saveState();updateStatus()};$("#swapLangBtn").onclick=()=>{let a=$("#sourceLang").value,b=$("#targetLang").value;$("#sourceLang").value=b;$("#targetLang").value=a;state.settings.sourceLang=b;state.settings.targetLang=a;saveState();updateStatus()};$("#styleChips").onclick=e=>{let b=e.target.closest("button[data-style]");if(!b)return;state.settings.style=b.dataset.style;saveState();$$("#styleChips button").forEach(x=>x.classList.toggle("selected",x===b))};$("#levelSelect").onchange=e=>{state.settings.level=e.target.value;saveState()};$("#speakerGender").onchange=e=>{state.settings.speakerGender=e.target.value;saveState()};$("#politeness").onchange=e=>{state.settings.politeness=e.target.value;saveState()};$("#audience").onchange=e=>{state.settings.audience=e.target.value;saveState()};$("#speechNote").oninput=e=>{state.settings.speechNote=e.target.value;saveState()};
$("#createMixBtn").onclick=async()=>{let text=$("#sourceEditor").innerText.trim();if(!text)return toast("まず文章を貼り付けてください。");if(text.length>10000)return toast("10,000文字以内にしてください。");if(state.settings.sourceLang===state.settings.targetLang)return toast("異なる言語を選んでください。");let items=extractItems(),a=await availability();if(a!=="unavailable"){try{makeArticle(await direct(items));return}catch(e){console.error(e);toast("端末翻訳に失敗したためChatGPT連携へ切り替えます。")}}$("#promptOutput").value=prompt(items);$("#jsonInput").value="";$("#jsonError").classList.add("hidden");showView("bridgeView")};
$("#copyPromptBtn").onclick=async()=>{try{await navigator.clipboard.writeText($("#promptOutput").value);toast("指示文をコピーしました")}catch{$("#promptOutput").select();document.execCommand("copy");toast("コピーしました")}};$("#pasteJsonBtn").onclick=async()=>{try{$("#jsonInput").value=await navigator.clipboard.readText()}catch{toast("長押しで貼り付けてください。")}};$("#importJsonBtn").onclick=()=>{try{let data=parse($("#jsonInput").value,extractItems());$("#jsonError").classList.add("hidden");makeArticle(data)}catch(e){$("#jsonError").textContent=`読み込めません：${e.message}`;$("#jsonError").classList.remove("hidden")}};
$("#backBtn").onclick=()=>showView("homeView");$("#homeBtn").onclick=()=>showView("homeView");$("#historyBtn").onclick=()=>openModal("historyModal");$("#savedBtn").onclick=$("#savedInReaderBtn").onclick=()=>openModal("savedModal");$$('[data-close-modal]').forEach(x=>x.onclick=()=>$("#"+x.dataset.closeModal).classList.add("hidden"));$("#readerArticle").onclick=e=>{let b=e.target.closest(".sentence");if(b)toggleSentence(b)};$("#mixSlider").oninput=e=>setMix(+e.target.value);$("#minusRatio").onclick=()=>setMix((activeArticle()?.mix||0)-10);$("#plusRatio").onclick=()=>setMix((activeArticle()?.mix||0)+10);$("#remixBtn").onclick=remix;$("#readerTitle").onchange=e=>{let a=activeArticle();if(a){a.title=e.target.value.trim()||"新しい文章";saveState()}};$("#speakTargetsBtn").onclick=speakTargets;$("#resetTapsBtn").onclick=()=>{let a=activeArticle();if(a){a.revealed=[];saveState();renderMeter();toast("計測をリセットしました")}};$("#applySuggestionBtn").onclick=e=>setMix(+e.target.dataset.value);$("#bubbleClose").onclick=closeBubble;$("#bubbleSpeak").onclick=()=>{let a=activeArticle();if(a&&activeBubbleSentence){let l=$("#bubbleLabel").textContent===langName(a.targetLang)?a.targetLang:a.sourceLang;speak($("#bubbleText").textContent,l)}};$("#bubbleSave").onclick=saveSentence;addEventListener("resize",closeBubble);addEventListener("scroll",closeBubble,{passive:true});
$("#historyList").onclick=e=>{let o=e.target.closest("[data-open]"),d=e.target.closest("[data-delete]");if(o){$("#historyModal").classList.add("hidden");openReader(o.dataset.open)}if(d){state.articles=state.articles.filter(a=>a.id!==d.dataset.delete);state.saved=state.saved.filter(x=>x.articleId!==d.dataset.delete);if(state.activeId===d.dataset.delete)state.activeId=null;saveState();renderHistory()}};$("#savedList").onclick=e=>{let s=e.target.closest("[data-speak]"),r=e.target.closest("[data-remove]");if(s){let x=state.saved.find(v=>v.id===s.dataset.speak);if(x)speak(x.target,x.lang)}if(r){state.saved=state.saved.filter(v=>v.id!==r.dataset.remove);saveState();renderSaved()}};charCount();updateStatus();if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}))}
bind();})();